backend:
  name: github
  repo: djbhoot/arafen-website
  branch: decap-11ty-migration
  base_url: https://decap-oauth.arafen-shovon.workers.dev

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Layout Tag", name: "tags", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SEO Title", name: "seoTitle", widget: "string", required: false }
      - { label: "Meta Description", name: "description", widget: "text" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
      - { label: "Featured Image Alt Text", name: "featuredImageAlt", widget: "string", required: false }
      - { label: "Category", name: "category", widget: "string", required: false }
      - { label: "Tags", name: "postTags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
